# Generated by Django 4.2.1 on 2023-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_blogmodel_images_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='images',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
